### ISSUE TITLE
Sort: A-Z shows unprintable character instead of "-"

### ISSUE THREAD

**Issue by birbilis** [seajax/seajax#19]
At filters pane, under a facet, the option that sorts facet values alphabetically says: "A-Z", but the "-" is some strange character that isn't shown correctly in IE11, nor Edge, nor Firefox. That character should be replaced by the humble "-" character in my opinion

**Comment by birbilis** [comment]
I see in seadragon-pivot-standalone-min.js the following:
d.push("Sort: "+r.orders[0].name)),d.push("Sort: Quantity"),g.push(gr),d.push("Sort: A\ufffdZ")

0xfffd Unicode character is that strange symbol (called "replacement character")
http://unicode.org/cldr/utility/character.jsp?a=FFFD

should instead use 002d (hyphen-minus)
http://unicode.org/cldr/utility/character.jsp?a=-&B1=Show
or one of the other similar looking ones (see the "Confuse" list shown there with similar looking chars (like hyphen, or minus etc.). Moving the mouse over each one at that list shows their name and can click to see more details

**Comment by sethobrien** [comment]
Agreed. I have no idea why it would be using that strange character.

**Comment by sethbrenith** [comment]
Fixed, thanks for reporting!
